name: Android Build & Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allows manual trigger via GitHub CLI

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'master'

    - name: Create .env file
      run: |
        echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
        echo "VAR_NAME=${{ vars.BASE_URL }}" >> .env

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
